import {Piada} from "../../piada";
export const LISTA_PIADAS: Piada[] = [
  { id: 1,
    author: "Bruno Nogueira",
    description: "eu sou 1 piada",
    markedAsFavorite: true},
  { id: 2,
    author: "Fabio Porchat",
    description: "eu sou 2 piada",
    markedAsFavorite: true},
  { id: 3,
    author: "Gilmário Vemba",
    description: "eu sou 3 piada",
    markedAsFavorite: true},
  { id: 4,
    author: "Gilmário Vemba",
    description: "eu sou 4 piada",
    markedAsFavorite: false},
  { id: 5,
    author: "Fernando Rocha",
    description: "eu sou 5 piada",
    markedAsFavorite: false},
  { id: 6,
    author: "Fernando Rocha",
    description: "eu sou 6 piada",
    markedAsFavorite: true},
  { id: 7,
    author: "Zlatan Ibrahimovic",
    description: "eu sou 7 piada",
    markedAsFavorite: true},
]
